const nodemailer = require('nodemailer');

const sendConfirmationEmail = async (req, res) => {
  console.log("ok?");
  
  // const transport = nodemailer.createTransport({
  //   host: "smtp.mailtrap.io",
  //   port: 2525,
  //   auth: {
  //     user: "1a2b3c4d5e6f7g", //example of generated by Mailtrap
  //     pass: "1a2b3c4d5e6f7g" //example of generated by Mailtrap
  //   }
  // });

  // const mailOptions = {
  //   from: 'from@example.com',
  //   to: '2022csci3100@gmail.com',
  //   subject: 'Test Nodemailer with Mailtrap',

  //   html: '<h1>Attachments</h1>',
  // };

  // transport.sendMail(mailOptions, (error, info) => {
  //   if (error) {
  //     return console.log(error);
  //   }
  //   console.log('Email sent: ' + info.response);
  // });

}

module.exports = { sendConfirmationEmail };


// // https://github.com/smartherd/Node-Get-Started/blob/master/8-send-email/solution-send-email.js

// //https://nodemailer.com/about/

// // function sendEmail(message) {

// //   return new Promise((res, rej) => {
// //     const transporter = nodemailer.createTransport({
// //       service: 'gmail',
// //       auth: {
// //         user: process.env.GOOGLE_USER,
// //         pass: process.env.GOOGLE_PASSWORD
// //       }
// //     })

// //     transporter.sendMail(message, function (err, info) {
// //       console.log("foin");
// //       if (err) {
// //         console.log("rej");
// //         rej(err);
// //       } else {
// //         console.log("inf");
// //         res(info);
// //       }
// //     })
// //   })
// // }

// const sendConfirmationEmail = async (req, res) =>  {

//   const transporter = nodemailer.createTransport({
//     service: 'gmail',
//     auth: {
//         user: '2022csci3100@gmail.com',
//         pass: 'Csci3100n2022'
//     }
//   });
//   console.log("okokokoko?");
//   const message = {
//     from: "2022csci3100@gmail.com",
//     // to: toUser.email // in production uncomment this
//     to:"2022csci3100@gmail.com",
//     subject: 'Your App - Activate Account',
//     html: `
//       <h3> Hello cyka </h3>
//       <p>Thank you for registering into our Application. Much Appreciated! Just one last step is laying ahead of you...</p>
//       <p>To activate your account please follow this link: <a target="_" href="/api/activate/user/activate </a></p>
//       <p>Cheers</p>
//       <p>Your Application Team</p>
//     `
//   }
//   transporter.sendMail(message, function(error, info){
//     console.log("okokokoko?");
//     if (error) {
//       console.log(error);
//     } else {
//       console.log('Email sent: ' + info.response);
//     }
//   });
//   // return sendEmail(message);
// }

// module.exports = { sendConfirmationEmail };
// // exports.sendResetPasswordEmail = ({ toUser, hash }) => {
// //   const message = {
// //     from: process.env.GOOGLE_USER,
// //     // to: toUser.email // in production uncomment this
// //     to: process.env.GOOGLE_USER,
// //     subject: 'Your App - Reset Password',
// //     html: `
// //       <h3>Hello ${toUser.username} </h3>
// //       <p>To reset your password please follow this link: <a target="_" href="${process.env.DOMAIN}/reset-password/${hash}">Reset Password Link</a></p>
// //       <p>Cheers,</p>
// //       <p>Your Application Team</p>
// //     `
// //   }

// //   // return sendEmail(message);
// // }